// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

#if os(iOS) || os(tvOS) || os(watchOS)
  import UIKit.UIImage
  typealias Image = UIImage
#elseif os(OSX)
  import AppKit.NSImage
  typealias Image = NSImage
#endif

// swiftlint:disable file_length
// swiftlint:disable type_body_length
enum Asset: String {
  case icCheck = "ic_check"
  case icClose = "ic_close"
  case icFlashAuto = "ic_flash_auto"
  case icFlashOff = "ic_flash_off"
  case icFlashOn = "ic_flash_on"
  case icInsertPhoto = "ic_insert_photo"
  case icLoop = "ic_loop"
  case icPhotoCamera = "ic_photo_camera"
  case icRadioButtonChecked = "ic_radio_button_checked"
  case icVideocam = "ic_videocam"
  case shutterButton = "shutter_button"
  case videoButton = "video_button"
  case videoButtonRec = "video_button_rec"
  case cmAddWhite = "cm_add_white"
  case cmArrowBackWhite = "cm_arrow_back_white"
  case cmArrowDownwardWhite = "cm_arrow_downward_white"
  case cmAudioLibraryWhite = "cm_audio_library_white"
  case cmAudioWhite = "cm_audio_white"
  case cmBellWhite = "cm_bell_white"
  case cmCheckWhite = "cm_check_white"
  case cmCloseWhite = "cm_close_white"
  case cmImageWhite = "cm_image_white"
  case cmMenuWhite = "cm_menu_white"
  case cmMicrophoneWhite = "cm_microphone_white"
  case cmMoreHorizWhite = "cm_more_horiz_white"
  case cmMoreVertWhite = "cm_more_vert_white"
  case cmMovieWhite = "cm_movie_white"
  case cmPauseWhite = "cm_pause_white"
  case cmPenWhite = "cm_pen_white"
  case cmPhotoCameraWhite = "cm_photo_camera_white"
  case cmPhotoLibraryWhite = "cm_photo_library_white"
  case cmPlayWhite = "cm_play_white"
  case cmSearchWhite = "cm_search_white"
  case cmSettingsWhite = "cm_settings_white"
  case cmShareWhite = "cm_share_white"
  case cmShuffleWhite = "cm_shuffle_white"
  case cmSkipBackwardWhite = "cm_skip_backward_white"
  case cmSkipForwardWhite = "cm_skip_forward_white"
  case cmStarWhite = "cm_star_white"
  case cmVideocamWhite = "cm_videocam_white"
  case cmVolumeHighWhite = "cm_volume_high_white"
  case cmVolumeMediumWhite = "cm_volume_medium_white"
  case cmVolumeOffWhite = "cm_volume_off_white"
  case icAddCircleOutlineWhite = "ic_add_circle_outline_white"
  case icAddCircleWhite = "ic_add_circle_white"
  case icAddWhite = "ic_add_white"
  case icArrowBackWhite = "ic_arrow_back_white"
  case icArrowDownwardWhite = "ic_arrow_downward_white"
  case icAudiotrackWhite = "ic_audiotrack_white"
  case icCameraFrontWhite = "ic_camera_front_white"
  case icCameraRearWhite = "ic_camera_rear_white"
  case icCheckWhite = "ic_check_white"
  case icCloseWhite = "ic_close_white"
  case icEditWhite = "ic_edit_white"
  case icEmailWhite = "ic_email_white"
  case icFavoriteBorderWhite = "ic_favorite_border_white"
  case icFavoriteWhite = "ic_favorite_white"
  case icFlashAutoWhite = "ic_flash_auto_white"
  case icFlashOffWhite = "ic_flash_off_white"
  case icFlashOnWhite = "ic_flash_on_white"
  case icHistoryWhite = "ic_history_white"
  case icHomeWhite = "ic_home_white"
  case icImageWhite = "ic_image_white"
  case icMenuWhite = "ic_menu_white"
  case icMoreHorizWhite = "ic_more_horiz_white"
  case icMoreVertWhite = "ic_more_vert_white"
  case icMovieWhite = "ic_movie_white"
  case icPhoneWhite = "ic_phone_white"
  case icPhotoCameraWhite = "ic_photo_camera_white"
  case icPhotoLibraryWhite = "ic_photo_library_white"
  case icPlaceWhite = "ic_place_white"
  case icSearchWhite = "ic_search_white"
  case icSettingsWhite = "ic_settings_white"
  case icShareWhite = "ic_share_white"
  case icStarBorderWhite = "ic_star_border_white"
  case icStarHalfWhite = "ic_star_half_white"
  case icStarWhite = "ic_star_white"
  case icVideocamWhite = "ic_videocam_white"
  case icVisibilityWhite = "ic_visibility_white"
  case errorIcon = "errorIcon"
  case errorIconLight = "errorIconLight"
  case errorIconSubtle = "errorIconSubtle"
  case infoIcon = "infoIcon"
  case infoIconLight = "infoIconLight"
  case infoIconSubtle = "infoIconSubtle"
  case successIcon = "successIcon"
  case successIconLight = "successIconLight"
  case successIconSubtle = "successIconSubtle"
  case warningIcon = "warningIcon"
  case warningIconLight = "warningIconLight"
  case warningIconSubtle = "warningIconSubtle"
  case icAttach = "ic_attach"
  case icBack = "ic_back"
  case icCancel = "ic_cancel"
  case icCart = "ic_cart"
  case icCheckSmall = "ic_check_small"
  case icCheckSmall0 = "ic_check_small_0"
  case icDd = "ic_dd"
  case icDeals = "ic_deals"
  case icDealsGrey = "ic_deals_grey"
  case icExplore = "ic_explore"
  case icExploreOn = "ic_explore_on"
  case icFacebookIcon = "ic_facebook-icon"
  case icFilter = "ic_filter"
  case icHeart = "ic_heart"
  case icHeartGrey = "ic_heart_grey"
  case icImg = "ic_img"
  case icInbox = "ic_inbox"
  case icInboxOn = "ic_inbox_on"
  case icLike = "ic_like"
  case icLikeOn = "ic_like_on"
  case icLogo = "ic_logo"
  case icLogoSmall = "ic_logo_small"
  case icMenu = "ic_menu"
  case icPicker = "ic_picker"
  case icProfile = "ic_profile"
  case icProfileOn = "ic_profile_on"
  case icSearch = "ic_search"
  case icSettings = "ic_settings"
  case icShare = "ic_share"
  case icShareStroked = "ic_share_stroked"
  case icSide = "ic_side"
  case icStore = "ic_store"
  case icStoreOn = "ic_store_on"
  case icToggleOff = "ic_toggle_off"
  case icToggleOn = "ic_toggle_on"
  case icUpload = "ic_upload"
  case icUu = "ic_uu"
  case superG = "super g"

  var image: Image {
    return Image(asset: self)
  }
}
// swiftlint:enable type_body_length

extension Image {
  convenience init!(asset: Asset) {
    self.init(named: asset.rawValue)
  }
}
